[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
PORT = "8000"
PYTHONPATH = "/app"
NIXPACKS_PYTHON_VERSION = "3.11"
